const cards=[
 ['01','O Eremita','⌁','A origem é solitária e sábia. Jun aparece como alguém que guardava conhecimento longe do ruído — um observador, um escriba, alguém procurado quando ninguém mais tinha respostas.','ORIGEM · posição 01','A força é discernimento; a sombra é o isolamento. Esta carta inicia a leitura porque mostra a memória mais antiga: aprender antes de falar, observar antes de conduzir.'],
 ['02','A Sacerdotisa','☾','A intuição não é novidade para ele. Esta carta confirma uma vida ligada ao segredo, aos sonhos e à leitura de sinais: uma mulher-oráculo, sacerdotisa ou guardiã de um templo interior.','ORIGEM · posição 02','A força é percepção; a sombra é guardar tanto silêncio que ninguém consegue alcançar você. Ao lado do Eremita, ela transforma o observador em guardião de um templo de montanha.'],
 ['03','Seis de Espadas','↝','Há uma travessia marcada. Em uma vida, ele foi exilado ou partiu por necessidade, conduzindo pessoas e histórias para um lugar seguro através de águas difíceis.','CUIDADO · posição 03','A força é conduzir em crise; a sombra é acreditar que partir é sempre abandonar. A carta dá movimento à sabedoria acumulada nas duas primeiras posições.'],
 ['04','Rainha de Copas','♧','O dom de acolher vem de uma curadora. Jun foi uma pessoa que cuidava de corpos e corações — parteira, herbalista ou conselheira — e conhecia a dor sem se assustar com ela.','CUIDADO · posição 04','A força é compaixão com técnica; a sombra é absorver o sofrimento alheio. Com o Seis de Espadas, ela especifica que Jun era a curadora que viajava para atender quem não podia chegar até ela.'],
 ['05','O Imperador','♜','Em outra passagem, ele teve autoridade. Não como um tirano, mas como líder de uma pequena comunidade: alguém que estabelecia ordem, protegia fronteiras e carregava decisões pesadas.','ESTRUTURA · posição 05','A força é liderança; a sombra é controle. O Imperador não fala de fama, mas de responsabilidade concreta por pessoas, alimento, abrigo e limites.'],
 ['06','Oito de Ouros','✧','A vida seguinte foi feita com as mãos. Ele foi artesão — especificamente, um construtor de objetos ritualísticos e símbolos — e encontrou paz na repetição paciente do ofício.','ESTRUTURA · posição 06','A força é aperfeiçoamento; a sombra é nunca achar o trabalho pronto. Ao lado do Imperador, indica o regente que também construía, em vez de apenas ordenar.'],
 ['07','A Lua','☽','Uma vida de dúvidas e pressentimentos. Jun foi um navegador ou intérprete de mapas noturnos, alguém que aprendeu a distinguir intuição de medo enquanto caminhava no escuro.','CONFLITO · posição 07','A força é imaginação; a sombra é confundir pressentimento com ameaça. A Lua introduz a vida em que Jun precisava navegar sem garantias e sem controlar o horizonte.'],
 ['08','Justiça','⚖','Ele também foi mediador: uma figura que registrava acordos, julgava conflitos e acreditava que a palavra escrita podia impedir novas guerras.','CONFLITO · posição 08','A força é equilíbrio; a sombra é endurecer o coração em nome da regra. Com A Lua, a Justiça mostra o navegador que virou mediador entre portos rivais.'],
 ['09','A Estrela','✦','O legado mais luminoso é de esperança. Nesta vida, ele foi mentor de jovens e deixou uma escola, uma oficina ou uma comunidade que continuou existindo depois de sua partida.','INTEGRAÇÃO · posição 09','A força é inspirar; a sombra é esperar reconhecimento pelo que oferece. A Estrela é a primeira carta em que Jun não precisa proteger tudo sozinho: ele acende uma luz para outros seguirem.'],
 ['10','O Mundo','◎','A carta final fecha o círculo: viajante, integrador, alguém que pertenceu a muitos lugares. O que ele era, no fundo, era uma ponte — entre pessoas, culturas e épocas.','INTEGRAÇÃO · posição 10','A força é completude; a sombra é nunca se sentir de um lugar só. O Mundo confirma que a quinta vida terminou com ensino, viagem e a integração de todas as anteriores.']
];
document.querySelector('#cards-grid').innerHTML=cards.map(c=>`<article class="tarot-card"><div><div class="card-number">CARTA ${c[0]}</div><div class="card-symbol">${c[2]}</div></div><div><h3>${c[1]}</h3><p>${c[3]}</p><div class="card-detail"><span>${c[4]}</span><p>${c[5]}</p></div></div></article>`).join('');
const lives=[
 ['VIDA 01 · A MAIS DISTANTE','O escriba do templo','O Eremita + A Sacerdotisa','Jun foi um escriba e guardião de um templo de montanha. Sua função era preservar relatos, sonhos e rituais. Viveu com pouco, mas era a pessoa a quem todos recorriam para compreender o invisível.'],
 ['VIDA 02 · A TRAVESSIA','A curadora do rio','Seis de Espadas + Rainha de Copas','Jun foi uma curadora e parteira que atravessava rios para atender famílias isoladas. Essa vida deixou o instinto de acolher, mas também o medo de não conseguir salvar todos.'],
 ['VIDA 03 · O PODER','O regente da fronteira','O Imperador + Oito de Ouros','Jun foi o líder de uma comunidade de artesãos numa região de fronteira. Construía muralhas e ferramentas com as próprias mãos. Aprendeu que proteger também é saber delegar.'],
 ['VIDA 04 · O MAPA','O navegador das marés','A Lua + Justiça','Jun foi navegador e mediador entre portos rivais. Lia estrelas, registrava tratados e carregava mensagens entre povos que não confiavam uns nos outros. Sua palavra evitou um conflito.'],
 ['VIDA 05 · O LEGADO','O mestre das pontes','A Estrela + O Mundo','Na vida mais recente, Jun foi professor e mentor de viajantes. Criou um lugar de aprendizado para pessoas de origens distintas. Partiu sabendo que seu trabalho continuaria em outras mãos.']
];
document.querySelector('#timeline').innerHTML=lives.map(l=>`<article class="life"><div class="life-index">${l[0]}</div><div><h3>${l[1]}</h3><p><strong>${l[2]}.</strong> ${l[3]}</p></div></article>`).join('');

// Céu vivo: estrelas discretas e conexões que respiram como uma constelação.
const sky=document.querySelector('#sky'), ctx=sky.getContext('2d');
let stars=[], w=0, h=0;
function resizeSky(){w=sky.width=window.innerWidth*devicePixelRatio;h=sky.height=window.innerHeight*devicePixelRatio;sky.style.width=window.innerWidth+'px';sky.style.height=window.innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const count=Math.min(115,Math.max(55,Math.floor(window.innerWidth/10)));stars=Array.from({length:count},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.35,a:Math.random()*.65+.2,s:Math.random()*.0008+.00025,p:Math.random()*Math.PI*2}));}
function drawSky(t){ctx.clearRect(0,0,innerWidth,innerHeight);const visible=stars.map(s=>({...s,alpha:s.a+Math.sin(t*s.s+s.p)*.12}));visible.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle=`rgba(237,220,173,${Math.max(.08,s.alpha)})`;ctx.fill();});for(let i=0;i<visible.length;i++){for(let j=i+1;j<visible.length;j++){const a=visible[i],b=visible[j],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);if(d<105){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=`rgba(176,151,213,${(1-d/105)*.13})`;ctx.lineWidth=.6;ctx.stroke();}}}requestAnimationFrame(drawSky);}
window.addEventListener('resize',resizeSky,{passive:true});resizeSky();requestAnimationFrame(drawSky);
